# Generated by Django 5.1.3 on 2024-12-09 06:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0002_remove_shoppingcart_total_price_shoppingcart_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferences", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RemoveField(
            model_name="aircrafttype",
            name="manufacturer",
        ),
        migrations.AlterField(
            model_name="airport",
            name="avg_security_time",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
