# Generated by Django 5.1.3 on 2024-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flights",
            "0003_profile_delete_user_remove_aircrafttype_manufacturer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
